name: Tests
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Node.version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-yarn-
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - run: yarn build
      - run: yarn lint
      - run: yarn workspace graphql-helix test
        env:
          CI: true
      - run: yarn workspace graphql-helix esm:test
