name: GraphQL Helix
on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node.version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn workspace graphql-helix lint
      - run: yarn workspace @graphql-helix/graphiql lint
      - run: yarn workspace graphql-helix build
      - run: yarn workspace graphql-helix test
        env:
          CI: true
